# Nombre de la aplicacion
spring.application.name=sistema-venta-pollo

# Configuraci\u00c3\u00b3n de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ventapollo

#Credenciales del usuario de BD
spring.datasource.username=usuario_pollo
spring.datasource.password=pollo123.

# Propiedades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Propiedades para el log
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#Esta informaci\u00c3\u00b3n se utiliza para obtener acceso a su storage.
firebase.bucket.name=sistema-ventapollo.firebasestorage.app
firebase.storage.path=sistema-ventapollo
firebase.json.path=firebase
firebase.json.file=sistema-ventapollo-firebase-adminsdk-fbsvc-405a83d146.json

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB